### ISSUE TITLE
请问聚类部分的代码在哪？

### ISSUE THREAD

**Issue by HanChen-HUST** [liun-online/HeCo#1]
作者您好，请问聚类部分的代码在哪呢？

**Comment by liun-online** [comment]
已邮箱回复

**Comment by kepsail** [comment]
你好，麻烦给我也发一下聚类代码，谢谢。
ymyang@stu.xidian.edu.cn

**Comment by liun-online** [comment]
在这里统一回复一下吧。
以下是聚类的部分代码，其中调用的api均为sklearn里的。

def evaluate_cluster(embeds, y, n_label):
    Y_pred = KMeans(n_label, random_state=0).fit(embeds).predict(embeds)
    nmi = normalized_mutual_info_score(y, Y_pred)
    ari = adjusted_rand_score(y, Y_pred)
    return nmi, ari
   
def evaluate_clu(dataset, embeds, label):
    if dataset =="acm":
      n_label = 3
    elif dataset =="dblp":
      n_label = 4
    elif dataset == "aminer":
      n_label = 4
    elif dataset == "freebase":
      n_label = 3
     
    embeds = embeds.cpu().data.numpy()
    label = np.argmax(label.cpu().data.numpy(), axis=-1)
    nmi, ari = evaluate_cluster(embeds, label, n_label)
    print("\t[clustering] nmi: {:.4f} ari: {:.4f}"
              .format(nmi, ari) )
