### ISSUE TITLE
Don't know the data type

### ISSUE THREAD

**Issue by junjiunian** [liun-online/HeCo#11]
Could you provide the type of data in the data folder? such as, the data types in files such as "pa.txt" and "pc.txt" in the "data>dblp" folder.

**Comment by liun-online** [comment]
'pa.txt' describes the interactions between paper index and author index (both start from 0). For example, the first line is '0\t262'. "pc.txt" is constructed in a similar way.

**Comment by junjiunian** [comment]
thank you for your answer :)~♥

**Comment by junjiunian** [comment]
Hello, I have another question. For example, in the acm dataset, what is the relationship between the data in the "train_60. npy" file, the data in the "pa.txt" file and the data in the "a_feat.npz" file? If possible, I want to know how these data files are generated.

**Comment by liun-online** [comment]
Sorry, I do not know what the meaning of "relationship". These three files are independent, and their functions are clear I think (node IDs for training, edges between paper and author, features of author).  You can just print these data and will know how to generate them.
