### ISSUE TITLE
数据预处理相关问题请教

### ISSUE THREAD

**Issue by GooLiang** [liun-online/HeCo#13]
作者您好，感谢您的工作。对于数据预处理部分有两个问题想请问一下：
1：请问下数据预处理部分的“关系.txt”是怎么获取的。按照论文所述应该是follow的MAGNN的数据预处理方法，但是以MAGNN的DBLP数据集举例来说，其中的paper_author.txt的内容与Heco中的pa.txt并不一致。
2：数据集划分中的train,test,val_20,40.60.npy的生成方式似乎没有在代码中公开，想请问下这块的代码是怎么生成的。
祝好！

**Comment by liun-online** [comment]
1. dblp数据的确是follow了MAGNN。在MAGNN提供的数据里，"paper_author.txt"里共有41794条数据。而“author_label.txt”中带label的author共有4057个，我们在"paper_author.txt"中保留其中有author标签的数据，这样就剩下19645条paper_author数据，这也是和MAGNN论文里表2提供的数据统计一致。之后，我们根据paper的原始index对筛选后的paper_author关系进行重排，再将paper和author分别从0开始重新编码，即可得到我们使用的dblp数据集。
2. 对数据集的划分即先随机分别选取1000个节点作为测试集和验证集，之后在剩下的节点中，每类选取20/40/60个节点作为训练集。不同case下的数据集没有任何关系，即train_40.npy中的节点不一定会包含train_20.npy中的节点，test_20.npy中的节点和test_40.npy中的节点也不一致。
