### ISSUE TITLE
The first term of Eq(4) is right?

### ISSUE THREAD

**Issue by HuizhaoWang** [liun-online/HeCo#3]
![image](https://user-images.githubusercontent.com/33713684/147064730-1d0b8909-57ba-476a-a79f-9dc834b02739.png)
hello，eq(4) is to compute the contribution of different type neighbors for node i, why the first term in eq(4) need to sum then average all node V in graph. In the words, the first term in eq(4) should be remove some parts.
![image](https://user-images.githubusercontent.com/33713684/147065640-86bd0b6c-fc6b-4291-b99b-c1f8e0375a71.png)

**Comment by liun-online** [comment]
The eq(4) is a process for self-attention. α_sc is attention vector, which is used to compute the importance of φ_m type neighbors for each node. Then we average them to get the mean importance of φ_m type neighbors in the whole HG. This operation is common, and you can refer to HAN for further comprehension.

**Comment by HuizhaoWang** [comment]
ok， thanks for your reply！
