### ISSUE TITLE
几个重要但却迷糊的问题？

### ISSUE THREAD

**Issue by HuizhaoWang** [liun-online/HeCo#4]
您好，看完文章，仍然存在几个疑惑，非常期待您能给出解答。
1、target node 是不是指的就是我们要去进行分类以及聚类的那一类节点（比如paper）？进一步讲，该方法是不是无法得到异构图中非target类型节点的表征，从而解决链接预测（比如paper与subject之间）等问题？
2、文中讲z^mp用于下游的应用（节点分类，聚类），是因为目标类型节点显式地（explicitly）参与到了z^mp的生成之中。这怎么理解，是指对于一个目标节点（target node i），其原路径邻居节点（meta-path based neighbors） 
![image](https://user-images.githubusercontent.com/33713684/147187956-159ed5ed-f63a-4e5b-9a99-5cafb6aa705d.png)
中只包含了与目标节点同种类型的节点？
3、eq(6)是GCN中拉普拉斯矩阵与节点特征进行聚合的方式，但是实际上GCN中还存在可训练参数W，为什么这里却没有，是省略了，还是这里确实就没有，如果本来就没有，背后的道理是啥？另外，看过你在文章中给出的例子，对于节点i的原路径邻居节点![image](https://user-images.githubusercontent.com/33713684/147187956-159ed5ed-f63a-4e5b-9a99-5cafb6aa705d.png)仍然存在疑惑，具体来讲，对于一个目标节点而言，其一条原路径上所有节点（包含目标类型节点和非目标类型节点）都转化为它的一阶邻居节点?路径上其他节点之间的边是否仍然保留，然后再进行信息聚合？
4、可以举个更详细点的例子，说明节点原始特征x_i是如何初始化的嘛？具体而言，图中所有类型的节点都是有original attribute的吗，遇到没有原始特征/属性的类型节点怎么办（随机初始化）？

**Comment by liun-online** [comment]
感谢对我们工作的关注！
1. target node的确是我们要分类的节点。其他类型节点的表征我们也能得到。在./code/module/heco.py的第27-29行，我们会通过映射得到每个类型的节点的embedding。此时，其他类型节点的输入feature是one-hot。你可以把它们的embedding拿来做链路预测，当然如果其他类型的节点也有相应的feature也要喂进来。
2. 只将z^mp应用于下游任务是针对于z^sc来说的。我们这个方法对于paper来说其实有两套embedding，z^mp和z^sc。但是z^sc未吸收paper的信息，因此效果不如z^mp，这一点在消融实验中也略有验证。
3. 第一个问题：我们这里是省略了w，代码中是有的。这里可能是我们的疏忽；第二个问题：基于元路径的邻居指的是，依据元路径，找元路径两端的节点。例如，目标paper是p1，元路径是p1-a1-p2，那么p2就是p1的基于元路径的邻居，在得到p1 embedding的过程中只吸收p2，不管a1。因此，p1基于pap的邻居，本质上都是p1的二阶邻居，类型为p。
4. 我们用到了四个数据集，其中ACM、DBLP、Freebase都只有目标类型节点的feature，而没有其他类型节点的feature，因此我们赋予其他类型节点one-hot类型编码；对于Aminer，所有节点都没有original feature，因此我们给所有节点都是one-hot 编码。对于没有原始特征/属性的节点，你可以随机初始化，也可以如我们这样one-hot，只要baseline保持一致就行（如果其他Baseline也需要考虑其他类型节点）

**Comment by HuizhaoWang** [comment]
非常感谢您的回答！
另外，因为我自身对生成对抗网络理解的缺乏，对Heco_gan的训练流程存在不确定。我的理解是先训练heco一定数量的epoch；然后再冻结heco参数，利用训练得到的z_sc和z_mp去再去训练GAN中的生成器（generator）和判别器（discriminator）一定数量的epoch；继而利用训练好的生成器（generator）再去针对目标节点生成其更强负样本，加入到原有heco的负样本中，再接着之前训练好的heco的参数（还是重头开始）训练heco? 
您看，我以上的理解是是否存在啥问题，或者有什么其他需要注意的地方？

**Comment by liun-online** [comment]
1、喂给判别器的是真实的正负例。例如对于z_sc下的节点i，我们在z_mp中选取它的正例以及负例，喂给判别器，使它能区分节点i在z_mp中的正负例情况。继而训练生成器，让它去迷惑判别器，这样生成器生成的就是节点i在z_mp中逼真的负例。
2、generator生成的负例加入到原有的正负例中，接着训练heco
