### ISSUE TITLE
Neighbor预处理问题

### ISSUE THREAD

**Issue by KennyNH** [liun-online/HeCo#5]
https://github.com/liun-online/HeCo/blob/81fbfad8c91147ab881c858e393cc69f2de491db/data/neibor.py#L17

dict.values()可以保证neighbor列表按照节点的索引序排列吗？我测了以下好像是乱序的，请问这是什么原因呢？

**Comment by liun-online** [comment]
你好，感谢对我们工作的关注！经过检查，发现你说的这个问题确实存在，但是这个只会影响到DBLP数据集上的结果。因为对于其他数据集来说，连边关系的txt都是从目标节点指向其他类型节点的。例如ACM数据集，它的连边文件分别是pa.txt和ps.txt，其里面每个条目都是由目标类型p指向a或s，而所有条目是按照p的索引排列好的，因此在neibor.py读取的时候不会出现你的这个问题。DBLP是因为目标类型是A，但是连边文件都是从p开始的，因此对于A类型来说是乱序的。我在写neibor.py的时候主要是按照ACM数据集来写的，因此并没注意到这个问题。感谢你的指正！
修改过之后，我在DBLP上重新跑了节点分类的实验，用的当前给出的超参数，未做调整，结果如下：
|Metric|Marco  |Marco  |Marco  | Micro |Micro |Micro | AUC | AUC | AUC |
| :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
|Split| 20|40|60 |20|40|60 | 20|40|60 |
| Old| 91.28±0.2|90.34±0.3|90.64±0.3 | 91.97±0.2|90.76±0.3|91.59±0.2  |98.32±0.1|98.06±0.1|98.59±0.1   |
| Update|91.05±0.0|90.11±0.4|90.52±0.4  |91.77±0.2|90.55±0.4|91.48±0.2  |98.25±0.1|98.02±0.1|98.53±0.1    |

可以看到，改过之后效果略有下降，但是还是优于baseline的。而且请注意，我们这里并没有对于改过之后的代码进行调参，只是用原有的参数，因此改过之后的最佳效果还会提高。我会将代码进行更新，感谢你指出的问题，希望可以继续关注我们的工作，有问题可以继续交流！

**Comment by KennyNH** [comment]
感谢回复！

**Comment by KennyNH** [comment]
感谢回复！

**Comment by liun-online** [comment]
代码已经修复
