### ISSUE TITLE
Positive Sample

### ISSUE THREAD

**Issue by DuanhaoranCC** [liun-online/HeCo#6]
Hello, the method of calculating the positive example proposed in the paper is very unique! However, some people are worried about the choice of its threshold. Most positive examples are actually pseudo positive examples, especially those with high threshold. For example DBLP, there are 1000, and more than half of them are inconsistent labels. What impact does this have on the model

**Comment by liun-online** [comment]
Hello, thanks for your attention!
This is a good question, and the method in paper is actually simple and heuristic. The number of 1000 is a hyper-parameter needed to tune, and it's the best choice in my grid search. Frankly, most postive samples belong to different classes as you say. But HeCo is an unsupervised method, so the process of selecting postives cannot be guided by labels. In your own application, you can involve labels into the process, and definitely match the nodes from the same class.

**Comment by DuanhaoranCC** [comment]
In addition, as far as I know, DGI is an algorithm for isomorphic graphs. How is it used on heterogeneous graphs?

**Comment by liun-online** [comment]
As far as I know, there are two ways to conduct methods for homogeneous graph on heterogeneous graph. The one way is to extract different meta-paths from dataset (e.g. APA, APCPA) and view these meta-path based adjacent metrix as homogeneous graphs, test them with DGI respectively, and select the best one as the result. You can refer to HAN. The other way is to concatenate all of the relations into an unified graph (e.g. simultaneously consider p-a, p-c and p-t relations), and neglect the difference of node types. In this way, you can get a big homogeneous graph finally.

**Comment by DuanhaoranCC** [comment]
Thank you!
