### ISSUE TITLE
关于聚类分析可视化用到的t-sne方法

### ISSUE THREAD

**Issue by WangYC-99** [liun-online/HeCo#7]
您好，我针对acm数据集利用您给出的聚类分析方法后，聚类分析结果还可以，只是在二维可视化的时候要将64维的embedding结果降维到二维，用了文章中提到的t-sne方法，但是又两个类别样本点在二维空间上的区分并不是像论文中的那样明显。不知道可否给出tsne降维的参数或者代码模块进行参考，谢谢！

**Comment by liun-online** [comment]
您好，关于t-sne的代码我并没有保留，我是从网上找的一个较常用的代码。而且随着随机种子的不同，每次获得的embedding不相同，所以tsne效果也不尽相同。我在论文中展示的是效果较好的某一次结果，轮廓系数是我们平均随机十次后的结果。
