### ISSUE TITLE
关于HAN的baseline实验设置

### ISSUE THREAD

**Issue by WangYC-99** [liun-online/HeCo#8]
抱歉打扰。文章中提到了将HAN作为baseline进行对比，想请教一下HAN这种有监督的端到端训练模型是如何设置对比实验的。感谢！

**Comment by liun-online** [comment]
您好，我们在做实验的时候，HAN就是当成普通的有监督模型进行训练的，对于某一设置，例如ACM的split20， 我们把训练集拿出来训练得到embedding，然后在同样的验证集测试集上，用同样的评测方法进行测试。

**Comment by WangYC-99** [comment]
感谢回复！
